name: "Terraform Infrastructure Deployment"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
  workflow_dispatch: # 🚀 This enables the manual "Run workflow" button in GitHub
permissions:
  contents: read
  pull-requests: write

jobs:
  terraform:
    name: "Terraform Action"
    runs-on: ubuntu-latest
    
    # Exporting Azure credentials as environment variables for the AzureRM provider & backend
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    # 1. Clone the repository code onto the GitHub runner
    - name: Checkout Code
      uses: actions/checkout@v6

    # 2. Install the specific version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: "1.8.0" # Match your local version preference

    # 3. Format validation check
    - name: Terraform Format Check
      run: terraform fmt -check

    # 4. Initialize Backend (Connects securely to your Azure Blob Container)
    - name: Terraform Init
      run: terraform init

    # 5. Dynamically Determine and Select Workspace
    # Maps 'develop' branch to 'dev' workspace, and 'main' branch to 'prod' workspace
    - name: Select Terraform Workspace
      run: |
        if [ "${{ github.ref_name }}" = "main" ]; then
          ENVIRONMENT="prod"
        else
          ENVIRONMENT="dev"
        fi
        echo "Target Environment: $ENVIRONMENT"
        terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT

    # 6. Generate execution plan
    - name: Terraform Plan
      run: terraform plan -input=false

    # 7. Apply Changes (Only executes on a direct push to develop or main branches)
    - name: Terraform Apply
      if: github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
